# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rgb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(height_field='height', upload_to=b'', width_field='width')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('rgb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rgb.RGB')),
            ],
        ),
    ]
